mi_boe_web/config/routes.rb
MiBoeWeb::Application.routes.draw do

  devise_for :users

  resources :searches
  
  resources :users do
    resources :subscriptions    
  end

  get "home/index"

  root :to => "home#index"

end

mi_boe_web/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    unless user.nil? # if the user is logged in
      can :manage, Subscription, :user_id => user.id
    end
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

mi_boe_web/app/models/search.rb
class Search < ActiveRecord::Base
  attr_accessor :responseHeader
  attr_accessor :response
  attr_accessor :facet_counts
  attr_accessor :highlighting

  DOCS_PER_QUERY = 10
end

mi_boe_web/app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
end

mi_boe_web/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

mi_boe_web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(User)
      user_subscriptions_url(resource_or_scope)
    else
      super
    end
  end
end

mi_boe_web/app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /
  def index
    @search = Search.new

    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

mi_boe_web/app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  # POST /searches
  # POST /searches.xml
  def create
    query = SolrAPI::Query.find(
      :one,
      :from => SolrAPI::Query.prefix,
      :params => {
        :q => (params[:search][:query].present? ? params[:search][:query] : '*:*'),
        :start => (params[:search][:start].present? ? params[:search][:start] : '0'),
        :fq => (params[:search][:fq].present? ? params[:search][:fq] : ''),
        :wt => 'json'
      }
    )
    @search = Search.new(query.attributes)

    respond_to do |format|
      format.html { render :action => 'show' }
      format.xml  { render :xml => @search, :status => :created, :location => @search }
    end
  end
end

mi_boe_web/app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!
  check_authorization
  skip_authorization_check :only => [:index]
  
  # GET /users/:user_id/subscriptions
  # GET /users/:user_id/subscriptions.xml
  def index
    @subscriptions = Subscription.find_all_by_user_id(current_user.id)
    authorize! :read, @subscriptions.first if @subscriptions.present?

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subscriptions }
    end
  end

  # GET /users/:user_id/subscriptions/new
  # GET /users/:user_id/subscriptions/new.xml
  def new
    @subscription = Subscription.new
    @subscription.user = current_user
    authorize! :new, @subscription

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subscription }
    end
  end

  # GET /users/:user_id/subscriptions/:subscription_id/edit
  def edit
    @subscription = Subscription.find(params[:id])
    authorize! :edit, @subscription
  end

  # POST /users/:user_id/subscriptions
  # POST /users/:user_id/subscriptions.xml
  def create
    @subscription = Subscription.new(params[:subscription])
    @subscription.user = current_user
    authorize! :create, @subscription

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to(user_subscriptions_url(current_user), :notice => 'Subscription was successfully created.') }
        format.xml  { render :xml => @subscription, :status => :created, :location => @subscription }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @subscription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/:user_id/subscriptions/:subscription_id
  # PUT /users/:user_id/subscriptions/:subscription_id.xml
  def update
    @subscription = Subscription.find(params[:id])
    authorize! :update, @subscription

    respond_to do |format|
      if @subscription.update_attributes(params[:subscription])
        format.html { redirect_to(user_subscriptions_url(current_user), :notice => 'Subscription was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subscription.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/:user_id/subscriptions/:subscription_id
  # DELETE /users/:user_id/subscriptions/:subscription_id.xml
  def destroy
    @subscription = Subscription.find(params[:id])
    authorize! :destroy, @subscription
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to(user_subscriptions_url(current_user)) }
      format.xml  { head :ok }
    end
  end
end

mi_boe_web/app/helpers/application_helper.rb
module ApplicationHelper
end

mi_boe_web/app/helpers/home_helper.rb
module HomeHelper
end

mi_boe_web/app/helpers/searches_helper.rb
module SearchesHelper
  def parse_facet_fields(category, category_i18n)
    result = '<h3>' + t(category_i18n) + '</h3>'
    attribute = @search.facet_counts.facet_fields.send(category)
    
    for i in 0..(attribute.count / 2 - 1)
      search_param = {:query => @search.responseHeader.params.q}
      search_param[:fq] = (@search.responseHeader.params.fq.present? ? (@search.responseHeader.params.fq + ' AND ') : '') + category + ":\"" + attribute[i*2].to_s + "\"" 
      result += '<br/> - ' + link_to(attribute[i*2].to_s + ' (' + attribute[i*2 + 1].to_s + ')', {:action => "create", :search => search_param}, {:method => 'post'})
    end
    result + '<br/><br/>'
  end

  def pagination
    result = ''
    if @search.response.numFound > 0
      if (@search.response.numFound / 10) < 20
        for i in 0..(@search.response.numFound / 10)
          result += (page_link i) + ' | '
        end
      elsif (@search.response.start / 10) < 5
        for i in 0..9
          result += (page_link i) + ' | '
        end
        result += ' ... ' + (page_link @search.response.numFound / 10)
      elsif (@search.response.start / 10) > (@search.response.numFound / 10 - 4) 
        result += (page_link 0) + ' ... '
        for i in (@search.response.numFound / 10 - 9)..(@search.response.numFound / 10)
          result += (page_link i) + ' | '
        end
      else
        result += (page_link 0) + ' ... '
        for i in (@search.response.start / 10 - 4)..(@search.response.start / 10 + 4)
          result += (page_link i) + ' | '
        end
        result += ' ... ' + (page_link @search.response.numFound / 10)
      end
    end
    result
  end
  
  private
    def page_link(i)
       if (i * 10) == @search.response.start
        (i + 1).to_s
      else
       link_to((i + 1).to_s, {:action => "create", :search => {:query => @search.responseHeader.params.q, :start => (i * 10).to_s, :fq => (@search.responseHeader.params.fq.present? ? @search.responseHeader.params.fq : '')}}, {:method => 'post'})
      end
    end
end

mi_boe_web/app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

mi_boe_web/app/views/home/index.html.erb
<div id='header'>
  <br/>
  <br/>
  <br/>
  <%= image_tag("logo_horiz_miboe.png") %>
  <br/>
  <br/>
  <br/>
  <%= render 'searches/form' %>
  <br/>
  <br/>
  <br/>
  <div>
  <table id="tableAbout"> 
    <tbody>
      <tr> 
        <td valign="top" align="justify" width="33%"> 
          <em><b><%= t('what_is_it.title') %></b></em><br /> 
      	 	<p align="justify"> 
            <%= t('what_is_it.content').html_safe %>
          </p> 
        </td> 
        <td valign="top" align="justify" width="33%"> 
          <em><b><%= t('how_does_it_work.title') %></b></em><br /> 
      		<p align="justify"> 
            <%= t('how_does_it_work.content_1') %>
          </p>
          <p align="justify">
            <%= t('how_does_it_work.content_2') %>
          </p>
        </td> 
        <td valign="top" align="center" width="33%"> 
      	  <em><b><%= t('who_are_we.title') %></b></em><br> 
      		<p align="justify"> 
            <b>Rubén Abad Agulló</b> - Scraping and front-end development
            <br/>
            <a href="https://github.com/rabad" target="_blank"><%= image_tag("github.png", :align=>"absmiddle", :border=>"0")%></a>
      		  <a href="http://es.linkedin.com/in/ruabag" target="_blank"><%= image_tag("linkedin.png", :align=>"absmiddle", :border=>"0")%></a> 
            <a href="http://twitter.com/ruabag" target="_blank"><%= image_tag("twitter.png", :align=>"absmiddle", :border=>"0") %></a>
      		  <br/> 
      		  <b>Alejandro González Díez</b> - Notifications and Scraping
            <br/>
            <a href="http://github.com/agonzalezdiez" target="_blank"><%= image_tag("github.png", :align=>"absmiddle", :border=>"0")%></a>
      		  <a href="http://es.linkedin.com/pub/alejandro-gonzalez-diez/30/109/9a6" target="_blank"><%= image_tag("linkedin.png", :align=>"absmiddle", :border=>"0")%></a> 
            <a href="http://www.twitter.com/nihilistBird" target="_blank"><%= image_tag("twitter.png", :align=>"absmiddle", :border=>"0") %></a>
      		  <br/>
      		  <b>Álvaro Martín Fraguas</b> - Front-end concept and development
            <br/>
      	    <a href="https://github.com/amartinfraguas" title="" target="_blank"><%= image_tag("github.png", :align=>"absmiddle", :border=>"0")%></a> 
      	    <a href="http://www.linkedin.com/pub/álvaro-mart%C3%ADn-fraguas/33/322/b33"><%= image_tag("linkedin.png", :align=>"absmiddle", :border=>"0")%></a> 
      		  <br/>
      		  <b>Leonardo Menezes da Silva</b> - Scraping and SolR setup
            <br/> 
            <a href="http://github.com/lmenezes" target="_blank"><%= image_tag("github.png", :align=>"absmiddle", :border=>"0")%></a>
      		  <a href="http://in.linkedin.com/in/leonardomenezess" title="" target="_blank"><%= image_tag("linkedin.png", :align=>"absmiddle", :border=>"0")%></a> 
            <a href="http://www.twitter.com/leonardomenezes" title="" target="_blank"><%= image_tag("twitter.png", :align=>"absmiddle", :border=>"0") %></a>
      		  <a href="http://lmenezes.com/?feed=rss2" title="" target="_blank"><%= image_tag("rss.png", :align=>"absmiddle", :border=>"0") %></a> 
          </p>
        </td> 
      </tr>     
    </tbody>
  </table>
  </div>
</div>

mi_boe_web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiBoeWeb</title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :all %>
    <%= csrf_meta_tag %>

    <script type="text/javascript">
    
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-23191720-1']);
      _gaq.push(['_setDomainName', '.miboe.es']);
      _gaq.push(['_trackPageview']);
    
      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    
    </script>
  </head>
  <body>
    <div id="mngb">
      <div id="gog">
        <div id="gbar">
          <nobr>
            <% if user_signed_in? %>
              <%= link_to(t('users.forms.edit_account'), edit_user_registration_path, :class=>"gb1") %> <%= link_to(t('subscriptions.one'), user_subscriptions_path(current_user), :class=>"gb1")  %> <%= link_to(t('users.forms.logout'), destroy_user_session_path, :class=>"gb1") %>
            <% else %>
              <%= link_to(t('users.forms.signin'), new_user_session_path, :class=>"gb1")  %> <%= link_to(t('users.forms.signup'), new_user_registration_path, :class=>"gb1")  %>
            <% end %>
          </nobr>
        </div>
      </div>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div id='wrapper'>
      <%= yield %>
      <div id='footer'>
        <%= link_to t('fork_us'), 'https://github.com/rocket-abredatos/mi_boe' %> - 
        <%= link_to t('follow_us'), 'http://twitter.com/#!/mi_boe' %> - 
        <%= link_to t('abredatos_challenge'), 'http://www.abredatos.es' %>
        <br/>
        <br/>
        <%= 'Powered by:' %>
        <br/>
        <%= link_to 'Ruby on Rails', 'http://rubyonrails.org' %> -
        <%= link_to 'Perl', 'http://www.perl.org' %> -
        <%= link_to 'Python', 'http://www.python.org' %> -
        <%= link_to 'Apache Solr', 'http://lucene.apache.org/solr' %> -
        <%= link_to 'Phusion Passenger', 'http://www.modrails.com' %> -
        <%= link_to 'Apache HTTP Server', 'http://httpd.apache.org' %> -
        <%= link_to 'MySQL', 'http://www.mysql.com' %> -
        <%= link_to 'Ubuntu', 'http://www.ubuntu.com' %>
      </div>
    </div>
  </body>
</html>

mi_boe_web/app/views/searches/_form.html.erb
<%= form_for(@search) do |f| %>
  <% if @search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% @search.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :query, :value => (@search.responseHeader.present? && (@search.responseHeader.params.q != '*:*')) ? @search.responseHeader.params.q : nil, :size => 80 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mi_boe_web/app/views/searches/show.html.erb
<div id='nav'>
  <div>
    <%= link_to (image_tag("logo_cuadrado_miboe.png", :border=>"0")), root_url %>
  </div>
  <br/>
  <div>
    <%= parse_facet_fields('seccion', 'section').html_safe %>
    <%= parse_facet_fields('organo', 'organ').html_safe %>
    <%= parse_facet_fields('rango', 'rank').html_safe %>
  </div>
</div>

<div id='main'>
  <%= render 'searches/form' %>
  <p class='results'>
    <% if @search.response.numFound > 0 %>
      <%= t('results_count_1') + (@search.response.start + 1).to_s + t('results_count_2') + (@search.response.numFound < Search::DOCS_PER_QUERY ? @search.response.numFound : (@search.response.start + Search::DOCS_PER_QUERY)).to_s + t('results_count_3') + @search.response.numFound.to_s %>
    <% else %>
      <%= t('no_results') %>
    <% end %>
  </p>
  <br />
  <br />
  <br />
  <div class="med" id="res" role="main">
    <div id="search">
      <div id="ires">
        <ol id="rso">
          <% @search.response.docs.each_with_index do |doc,i| %>
            <li class="g w0 knavi">
              <div class="vsc">
                <div class="vspi">
                </div>
                <span class="tl">
                  <h3 class="r">
                    <%= link_to(doc.titulo, doc.url, :class=>"l") %>
                  </h3>
                </span>
                <div class="s">
                  <%= strip_tags(doc.textoSnippet) %>...
                  <br />
                  <span class="f">
                    <span class="mft">
                      Fecha: 
                    </span>
                    <%= doc.fecha.strftime('%d-%m-%Y') %>
                    <span class="mft">
                      Órgano: 
                    </span>
                    <%= doc.organo %>
                     - 
                    <span class="mft">
                      Sección: 
                    </span>
                    <%= doc.seccion %>
                     - 
                    <%= link_to (image_tag("application_xml.png", :align=>"absmiddle", :width=>"24px", :height=>"24px", :border=>"0")), doc.url %>
                    <%= link_to (image_tag("application_pdf.png", :align=>"absmiddle", :width=>"24px", :height=>"24px", :border=>"0")), doc.urlPDF %>
                  </span>
                </div>
              </div>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
  <div id='pagination'>
    <p>
      <%= pagination.html_safe %>
    </p>
  </div>
</div>

mi_boe_web/app/views/subscriptions/_form.html.erb
<%= form_for([current_user,@subscription], :url => (@subscription.new_record? ? user_subscriptions_path(current_user) : user_subscription_path(current_user,@subscription)), :html => { :method => (@subscription.new_record? ? :post : :put) }) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('subscriptions.keywords') %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mi_boe_web/app/views/subscriptions/edit.html.erb
<table id="form">
  <tr>
    <td>
      <%= link_to (image_tag("logo_cuadrado_miboe.png", :border=>"0")), root_url %>
    </td>
    <td>
      <h1><%= t('subscriptions.editing') %></h1>
      <%= render 'form' %>
      <p><%= link_to t('back'), user_subscriptions_path(current_user) %></p>
    </td>
  </tr>
</table>

mi_boe_web/app/views/subscriptions/index.html.erb
<table id="subs">
  <tr>
    <td width="30%">
      <%= link_to (image_tag("logo_cuadrado_miboe.png", :border=>"0")), root_url %>
    </td>
    <td width="70%">
      <h1><%= t('subscriptions.listing') %></h1>
        <table>
        <tr>
          <th><%= t('subscriptions.keywords') %></th>
          <th></th>
          <th></th>
        </tr>
        <% @subscriptions.each do |subscription| %>
        <tr>
          <td><p><%= subscription.keywords %></p></td>
          <td><p><%= link_to t('edit'), edit_user_subscription_path(current_user,subscription) %></p></td>
          <td><p><%= link_to t('destroy'), user_subscription_path(current_user,subscription), :confirm => t('users.forms.sure'), :method => :delete %></p></td>
        </tr>
        <% end %>
      </table>
      <br />
      <p><%= link_to t('subscriptions.new'), new_user_subscription_path(current_user) %></p>
    </td>
</table>

mi_boe_web/app/views/subscriptions/new.html.erb
<table id="form">
  <tr>
    <td>
      <%= link_to (image_tag("logo_cuadrado_miboe.png", :border=>"0")), root_url %>
    </td>
    <td>
      <h1><%= t('subscriptions.new')%></h1>
      <p>
      <%= render 'form' %>
      </p>
      <p><%= link_to t('back'), user_subscriptions_path(current_user) %></p>
    </td>
  </tr>
</table>